refactor(kdrive-desktop-release.yml): restore release notes check step for validation

diff --git a/.github/workflows/kdrive-desktop-release.yml b/.github/workflows/kdrive-desktop-release.yml
--- a/.github/workflows/kdrive-desktop-release.yml
+++ b/.github/workflows/kdrive-desktop-release.yml
@@ -77,30 +77,27 @@ jobs:
     needs: get-version
     runs-on: [ self-hosted, Linux, X64 ]
     steps:
-      - name: Bypass this step for test purposes
-        run: echo "This step is bypassed for test purposes"; exit 0
+      - name: Checkout the PR
+        uses: actions/checkout@v4
+
+      - name: Check release notes
+        run: |
+          VERSION_NUMBER="${{ needs.get-version.outputs.kDrive_version }}"
+          BASE_NAME="kDrive-${VERSION_NUMBER}"
+          BASE_PATH="./release_notes/${BASE_NAME}"
+          OS=( "win" "linux" "macos" )
+          LANGUAGES=( "fr" "de" "es" "it" )
+          for os in "${OS[@]}"; do
+            for lang in "${LANGUAGES[@]}"; do
+              FILE="${BASE_PATH}/kDrive-${VERSION_NUMBER}-${os}-${lang}.html"
+              if [ ! -f "$FILE" ]; then
+                echo "Release notes file not found: $FILE"
+                exit 1
+              fi
+            done
+          done
+          echo "All release notes files are present."
         shell: bash
-#      - name: Checkout the PR
-#        uses: actions/checkout@v4
-#
-#      - name: Check release notes
-#        run: |
-#          VERSION_NUMBER="${{ needs.get-version.outputs.kDrive_version }}"
-#          BASE_NAME="kDrive-${VERSION_NUMBER}"
-#          BASE_PATH="./release_notes/${BASE_NAME}"
-#          OS=( "win" "linux" "macos" )
-#          LANGUAGES=( "fr" "de" "es" "it" )
-#          for os in "${OS[@]}"; do
-#            for lang in "${LANGUAGES[@]}"; do
-#              FILE="${BASE_PATH}/kDrive-${VERSION_NUMBER}-${os}-${lang}.html"
-#              if [ ! -f "$FILE" ]; then
-#                echo "Release notes file not found: $FILE"
-#                exit 1
-#              fi
-#            done
-#          done
-#          echo "All release notes files are present."
-#        shell: bash
 
 # Build apps
   build-Windows:
@@ -218,7 +215,7 @@ jobs:
           pattern: win-release-artifacts-*
           merge-multiple: true
 
-      #- name: Download macOS artifacts
+      #- name: Download macOS artifacts # TODO
       #  uses: actions/download-artifact@v4
       #  with:
       #    path: build-macos
