Setup env var for nightly and CI only tests.

diff --git a/.github/workflows/nightly-all.yml b/.github/workflows/nightly-all.yml
--- a/.github/workflows/nightly-all.yml
+++ b/.github/workflows/nightly-all.yml
@@ -1,13 +1,9 @@
-name: Windows kDrive desktop CI
+name: Nightly tests kDrive desktop - All OS 
 
 on:
-  pull_request:
-    types: [synchronize, review_requested]
-
-concurrency:
-  group: windows-${{ github.head_ref }}
-  cancel-in-progress: true
-
+    schedule:
+        - cron: '0 0 * * *'
+  
 env:
   KDRIVE_TEST_CI_API_TOKEN: ${{ secrets.KDRIVE_TOKEN }}
   KDRIVE_TEST_CI_ACCOUNT_ID: ${{ vars.KDRIVE_TEST_CI_ACCOUNT_ID }}
@@ -18,10 +14,10 @@ env:
   KDRIVE_TEST_CI_REMOTE_PATH: ${{ vars.KDRIVE_TEST_CI_REMOTE_PATH }}
   KDRIVE_TEST_CI_8MO_PARTITION_PATH: ${{ vars.KDRIVE_TEST_CI_8MO_PARTITION_PATH_WIN }}
   KDRIVE_TEST_CI_RUNNING_ON_CI: true
-
+  KDRIVE_TEST_CI_NIGHTLY : true
 
 jobs:
-  build-kDrive:
+  Windows:
     runs-on: [ self-hosted, Windows, desktop-kdrive ]
 
     steps:
@@ -63,19 +59,7 @@ jobs:
 
       - name: Execute tests
         run: |
-          $env:COVFILE="$pwd\src\test.cov"
-          & "cov01.exe" "-1" # coverage on
           ./infomaniak-build-tools/run-tests.ps1
-
-      - name: Compute code coverage
-        if: false
-        run : |
-          rm -Force -ErrorAction SilentlyContinue BullseyeCoverageExclusions
-          echo "exclude folder 3rdparty/\nexclude folder ../" >> BullseyeCoverageExclusions
-          $env:COVFILE="$pwd\src\test.cov"
-          & "cov01.exe" "-0" # coverage off
-          & "covselect.exe" "--import" "BullseyeCoverageExclusions"
-          & "covxml.exe" "-f" "$env:COVFILE" "-o" "coverage.xml"
 
       - name: Install sonar-scanner
         if: false
@@ -97,7 +81,6 @@ jobs:
             --define sonar.sources="src"
             --define sonar.exclusions="src/3rdparty/**"
             --define sonar.cfamily.compile-commands="build-windows/build/compile_commands.json"
-            --define sonar.cfamily.bullseye.reportPaths="coverage.xml"
 
       - name: Upload tests logs artifacts
         uses: actions/upload-artifact@v4
@@ -110,3 +93,91 @@ jobs:
 
       - name: Clean-up generated code
         run : powershell ./infomaniak-build-tools/windows/build-drive.ps1 -clean all
+
+  MacOS:
+    runs-on: [ self-hosted, macOS, desktop-kdrive ]
+
+    steps:
+      - name: Clean-up XCode DerivedData
+        run : rm -rf /Users/runner/Library/Developer/Xcode/DerivedData
+        
+      - name: Checkout the code
+        uses: actions/checkout@v4.1.1
+        with:
+          ref: ${{ github.head_ref }}
+          submodules: recursive
+
+      - name: Grant empty trash script execute permission
+        run : chmod +x ./infomaniak-build-tools/empty_drive_trash.sh
+      - name: Empty drive's trash
+        run : ./infomaniak-build-tools/empty_drive_trash.sh
+
+      - name: Unlock keychain to use the certificate
+        run : security unlock-keychain -p '${{ secrets.KEYCHAIN_PASSWORD }}' login.keychain
+
+      - name: Grant building script execute permission
+        run : chmod +x ./infomaniak-build-tools/macos/build-ci.sh
+      - name: Build kDrive desktop
+        run : ./infomaniak-build-tools/macos/build-ci.sh
+
+      - name: Grant tests script execute permission
+        run : chmod +x ./infomaniak-build-tools/run-tests.sh
+      - name: Execute tests
+        run : ./infomaniak-build-tools/run-tests.sh
+
+      - name: Get the path to kDrive-logdir
+        run : echo "logdir_path="$(find /private/var/folders/ -name kDrive-logdir 2>/dev/null)"" >> $GITHUB_ENV
+        if  : success() || failure()
+
+      - name: Upload tests logs artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: macos-tests-logs
+          path: ${{ env.logdir_path }}/*
+          retention-days: 3
+          overwrite: true
+        if: contains(env.logdir_path, 'kDrive-logdir') && (success() || failure())
+
+      - name: Clean the log directory
+        if  : contains(env.logdir_path, 'kDrive-logdir')
+        run : rm -rf ${{ env.logdir_path }}/*
+        continue-on-error: true
+
+      - name: Clean-up generated code
+        run : rm -rf build-macos
+
+  Linux:
+    runs-on: [ self-hosted, Linux, X64, desktop-kdrive ]
+
+    steps:
+      - name: Checkout the PR
+        uses: actions/checkout@v4.1.1
+        with:
+          ref: ${{ github.head_ref }}
+          submodules: recursive
+
+      - name: Clean the log directory
+        run : rm -rf /tmp/kDrive-logdir/*
+
+      - name: Grant building script execute permission
+        run : chmod +x ./infomaniak-build-tools/linux/build-ci-amd64.sh
+      - name: Build kDrive desktop
+        run : ./infomaniak-build-tools/linux/build-ci-amd64.sh -u
+
+      - name: Grant tests script execute permission
+        run : chmod +x ./infomaniak-build-tools/run-tests.sh
+      - name: Execute tests
+        run : ./infomaniak-build-tools/run-tests.sh
+
+      - name: Upload tests logs artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: linux-tests-logs
+          path: /tmp/kDrive-logdir/*
+          retention-days: 3
+          overwrite: true
+        if: always()
+
+      - name: Clean-up generated code
+        run : rm -rf build-linux
+
